### ISSUE TITLE
bob-plugin-openai-polisher 剥离用于润色的需要更新

### ISSUE THREAD

**Issue by ChinJCheung** [nextai-translator/bob-plugin-openai-polisher#33]
这个专门用于润色的好像不能使用了，相同的url和 api 另外一个可以使用，但是这个是接口未返回结果

**Comment by liby** [comment]
https://github.com/openai-translator/bob-plugin-openai-polisher/releases/tag/v3.0.0

**Comment by ChinJCheung** [comment]
> https://github.com/openai-translator/bob-plugin-openai-polisher/releases/tag/v3.0.0

thanks
